<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RefOrganisasi extends \Application\Entity\RefOrganisasi implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'parentOrganisasiId', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'kode', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'parentKode', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'nama', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'akronim', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'jabatanKepala', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'pimpinanDefinitif', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'pimpinanPlt', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'pimpinanPlh', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'eselon', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'jenisEselon', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'tingkatan', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'metaDtCreate', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'metaCreateBy', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'metaDtUpdate', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'metaUpdateBy'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'parentOrganisasiId', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'kode', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'parentKode', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'nama', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'akronim', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'jabatanKepala', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'pimpinanDefinitif', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'pimpinanPlt', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'pimpinanPlh', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'eselon', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'jenisEselon', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'tingkatan', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'metaDtCreate', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'metaCreateBy', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'metaDtUpdate', '' . "\0" . 'Application\\Entity\\RefOrganisasi' . "\0" . 'metaUpdateBy'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (RefOrganisasi $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getParentOrganisasiId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentOrganisasiId', []);

        return parent::getParentOrganisasiId();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentOrganisasiId(?string $parentOrganisasiId): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentOrganisasiId', [$parentOrganisasiId]);

        return parent::setParentOrganisasiId($parentOrganisasiId);
    }

    /**
     * {@inheritDoc}
     */
    public function getKode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKode', []);

        return parent::getKode();
    }

    /**
     * {@inheritDoc}
     */
    public function setKode(?string $kode): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKode', [$kode]);

        return parent::setKode($kode);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentKode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentKode', []);

        return parent::getParentKode();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentKode(?string $parentKode): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentKode', [$parentKode]);

        return parent::setParentKode($parentKode);
    }

    /**
     * {@inheritDoc}
     */
    public function getNama(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNama', []);

        return parent::getNama();
    }

    /**
     * {@inheritDoc}
     */
    public function setNama(?string $nama): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNama', [$nama]);

        return parent::setNama($nama);
    }

    /**
     * {@inheritDoc}
     */
    public function getAkronim(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAkronim', []);

        return parent::getAkronim();
    }

    /**
     * {@inheritDoc}
     */
    public function setAkronim(?string $akronim): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAkronim', [$akronim]);

        return parent::setAkronim($akronim);
    }

    /**
     * {@inheritDoc}
     */
    public function getJabatanKepala(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJabatanKepala', []);

        return parent::getJabatanKepala();
    }

    /**
     * {@inheritDoc}
     */
    public function setJabatanKepala(?string $jabatanKepala): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJabatanKepala', [$jabatanKepala]);

        return parent::setJabatanKepala($jabatanKepala);
    }

    /**
     * {@inheritDoc}
     */
    public function getPimpinanDefinitif(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPimpinanDefinitif', []);

        return parent::getPimpinanDefinitif();
    }

    /**
     * {@inheritDoc}
     */
    public function setPimpinanDefinitif(?string $pimpinanDefinitif): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPimpinanDefinitif', [$pimpinanDefinitif]);

        return parent::setPimpinanDefinitif($pimpinanDefinitif);
    }

    /**
     * {@inheritDoc}
     */
    public function getPimpinanPlt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPimpinanPlt', []);

        return parent::getPimpinanPlt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPimpinanPlt(?string $pimpinanPlt): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPimpinanPlt', [$pimpinanPlt]);

        return parent::setPimpinanPlt($pimpinanPlt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPimpinanPlh(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPimpinanPlh', []);

        return parent::getPimpinanPlh();
    }

    /**
     * {@inheritDoc}
     */
    public function setPimpinanPlh(?string $pimpinanPlh): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPimpinanPlh', [$pimpinanPlh]);

        return parent::setPimpinanPlh($pimpinanPlh);
    }

    /**
     * {@inheritDoc}
     */
    public function getEselon(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEselon', []);

        return parent::getEselon();
    }

    /**
     * {@inheritDoc}
     */
    public function setEselon(?string $eselon): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEselon', [$eselon]);

        return parent::setEselon($eselon);
    }

    /**
     * {@inheritDoc}
     */
    public function getJenisEselon(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJenisEselon', []);

        return parent::getJenisEselon();
    }

    /**
     * {@inheritDoc}
     */
    public function setJenisEselon(?string $jenisEselon): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJenisEselon', [$jenisEselon]);

        return parent::setJenisEselon($jenisEselon);
    }

    /**
     * {@inheritDoc}
     */
    public function getTingkatan(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTingkatan', []);

        return parent::getTingkatan();
    }

    /**
     * {@inheritDoc}
     */
    public function setTingkatan(?int $tingkatan): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTingkatan', [$tingkatan]);

        return parent::setTingkatan($tingkatan);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaDtCreate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaDtCreate', []);

        return parent::getMetaDtCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaDtCreate(?\DateTimeInterface $metaDtCreate): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaDtCreate', [$metaDtCreate]);

        return parent::setMetaDtCreate($metaDtCreate);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaCreateBy(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaCreateBy', []);

        return parent::getMetaCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaCreateBy(?string $metaCreateBy): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaCreateBy', [$metaCreateBy]);

        return parent::setMetaCreateBy($metaCreateBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaDtUpdate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaDtUpdate', []);

        return parent::getMetaDtUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaDtUpdate(?\DateTimeInterface $metaDtUpdate): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaDtUpdate', [$metaDtUpdate]);

        return parent::setMetaDtUpdate($metaDtUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaUpdateBy(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaUpdateBy', []);

        return parent::getMetaUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaUpdateBy(?string $metaUpdateBy): \Application\Entity\RefOrganisasi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaUpdateBy', [$metaUpdateBy]);

        return parent::setMetaUpdateBy($metaUpdateBy);
    }

}
