<?php 
//use Application\Entity\RefButirKegiatan;
$optionsButirKegiatan = "";
$tr = "";
if(isset($this->kegiatan)){
    foreach ($this->kegiatan as $k ) {
        // echo $k->getIdJenjangJabatanFungsional()->getNama() ."<br/>";
        // echo $k->getIdSubUnsur()->getIdUnsur()->getNama() ."<br/>";
        // echo $k->getIdSubUnsur()->getNama() ."<br/>";
        // echo $k->getKegiatan() ."<br/>";
        $jenjang = $k->getIdJenjangJabatanFungsional()->getNama();
        $unsur = $k->getIdSubUnsur()->getIdUnsur()->getNama();
        $subUnsur =    $k->getIdSubUnsur()->getNama();
         $kegiatan = $k->getKegiatan();
         $ak = $k->getAngkaKredit()?$k->getAngkaKredit():0 ;
         $kode = $k->getKode();
     
         
     
        $text = '['.$jenjang. '] Unsur: '. $unsur.' '.$subUnsur.' '.$kegiatan;
        $value = $k->getId();
        $optionsButirKegiatan .= "<option value='$value'>$text</option>";
     
        $tr .= "<tr>".
             "<td>$jenjang</td>". 
             "<td>$kode</td>". 
             "<td>$unsur</td>".
             "<td>$subUnsur</td>".
             "<td>$kegiatan</td>".
             "<td>$ak</td></tr>";
     }
}


function toDataTable($tr){
    $datatable = "<table class='Datatable table display' id='dtFormasi'>
    <thead>
    <tr>
        <th>Unit Kerja</th>
        <th>Jenjang</th>
        <th>Formasi</th>
        <th>Bezetting</th>
    </tr>
    </thead>
    <tbody>
    $tr
    </tbody>
    </table>";
    return $datatable;
}

?>

<div class="row">
<div class=" col-12">
<div class="card card-primary">
    <div class="card-header">
    <h3 class="card-title">Daftar Formasi</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form">
    <div class="card-body">
        <?=toDataTable($tr);?>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    </form>
</div>
<!-- /.card -->
</div>
</div>

<?php
$this->inlineScript()->captureStart();
echo <<<JS

    $('.select2').select2();

    $(".nav-item").removeClass("menu-open");
    $(".nav-item a").removeClass("active");


    $("#nav-item-data-referensi").addClass("menu-open");
    $("#nav-item-data-referensi > a").addClass("active");
    $("#nav-item-ref-formasi > a").addClass("active");

    $('select').change(function(){
        //location.href = $(this).val();
    });

    $("#dtFormasi").DataTable({
      "responsive": true,
      "autoWidth": false,
    });

JS;
$this->inlineScript()->captureEnd();
