<?php 
//use Application\Entity\RefJenjangJabatanFungsional;
$optionsJabatanFungsional = "";
$tr = "";
if(isset($this->jabatanFungsional)){
    foreach ($this->jabatanFungsional as $jf ) {
        $kode = $jf->getKode();
        $nama = $jf->getNama();
        $text = '['.$kode. ']' .$nama;
        $value = $k->getId();
        $optionsJabatanFungsional .= "<option value='$value'>$text</option>";
        $tr .= "<tr>".
            "<td>$kode</td>". 
            "<td>$nama</td>";
    }
}

function toDataTable($tr){
    $datatable = "<table class='Datatable table display' id='dtJenjangJabatanFungsional'>
    <thead>
    <tr>
        <th>kode</th>
        <th>Nama</th>
    </tr>
    </thead>
    <tbody>
    $tr
    </tbody>
    </table>";
    return $datatable;
}

?>

<div class="row">
    <div class=" col-12">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Daftar Jabatan Fungsional</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form">
                <div class="card-body">
                    <?=toDataTable($tr);?>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                <button type="button" class="btn btn-primary float-right">Tambah Jabatan Fungsional</button>
                </div>
            </form>
        </div>
        <!-- /.card -->
    </div>
</div>

<?php
$this->inlineScript()->captureStart();
echo <<<JS

    $('.select2').select2({
        theme: 'bootstrap4'
    })

    $("#nav-item-data-referensi").addClass("menu-open");
    $("#nav-item-data-referensi > a").addClass("active");
    $("#nav-item-ref-jabatan-fungsional > a").addClass("active");

    $('select').change(function(){
        //location.href = $(this).val();
    });

    $("#dtJenjangJabatanFungsional").DataTable({
      "responsive": true,
      "autoWidth": false,
    });

JS;
$this->inlineScript()->captureEnd();