<?php 
//use Application\Entity\RefJenjangJabatanFungsional;
$optionsJenjangJabatanFungsional = "";
$optionsJabatanFungsional = "";
$tr = "";
if(isset($this->jabatanFungsional)){
    foreach ($this->jabatanFungsional as $jf ) {
        $kode = $jf->getKode();
        $nama = $jf->getNama();
        $text = '['.$kode. ']' .$nama;
        $value = $k->getId();
        $optionsJabatanFungsional .= "<option value='$value'>$text</option>";
    }
}

if(isset($this->jenjangJabatanFungsional)){
    foreach ($this->jenjangJabatanFungsional as $k ) {
        $nama = $k->getNama();
        $kode = $k->getKode();
        $tingkat = $k->getTingkat();
    
       $tr .= "<tr>".
            "<td>$kode</td>". 
            "<td>$nama</td>".
            "<td>$tingkat</td>";
    }
}

function toDataTable($tr){
    $datatable = "<table class='Datatable table display' id='dtJenjangJabatanFungsional'>
    <thead>
    <tr>
        <th>kode</th>
        <th>Nama</th>
        <th>Tingkat</th>
    </tr>
    </thead>
    <tbody>
    $tr
    </tbody>
    </table>";
    return $datatable;
}

?>

<div class="row">
    <div class=" col-12">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Jabatan Fungsional</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->

            <div class="card-body">

                <div class="row">

                    <div class="col-12">
                        <div class="form-group select2-purple">
                            <label>Minimal</label>
                            <select class="form-control select2"  style="width: 100%;">
                                <option selected="selected">Alabama</option>
                                <option>Alaska</option>
                                <option>California</option>
                                <option>Delaware</option>
                                <option>Tennessee</option>
                                <option>Texas</option>
                                <option>Washington</option>
                            </select>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->

            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="button" class="btn btn-primary float-right">Tambah Jabatan Fungsional</button>
            </div>

        </div>
        <!-- /.card -->
    </div>
</div>

<div class="row">
    <div class=" col-12">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Daftar jenjangJabatanFungsional</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form">
                <div class="card-body">
                    <?=toDataTable($tr);?>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                <button type="button" class="btn btn-primary float-right">Tambah Jenjang Jabatan Fungsional</button>
                </div>
            </form>
        </div>
        <!-- /.card -->
    </div>
</div>

<?php
$this->inlineScript()->captureStart();
echo <<<JS

    $('.select2').select2({
        theme: 'bootstrap4'
    })

    $("#nav-item-data-referensi").addClass("menu-open");
    $("#nav-item-data-referensi > a").addClass("active");
    $("#nav-item-ref-jenjang-jabatan-fungsional > a").addClass("active");

    $('select').change(function(){
        //location.href = $(this).val();
    });

    $("#dtJenjangJabatanFungsional").DataTable({
      "responsive": true,
      "autoWidth": false,
    });

JS;
$this->inlineScript()->captureEnd();