<?php 

?>

<div class="row">
<div class=" col-12">
<div class="card card-primary">
    <div class="card-header">
    <h3 class="card-title">Struktur Organisasi</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    
    <div class="card-body">
        <h3>TREE VIEW</h3>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
    </div>

</div>
<!-- /.card -->
</div>
</div>

<?php
$this->inlineScript()->captureStart();
echo <<<JS

    $('.select2').select2();

    $(".nav-item").removeClass("menu-open");
    $(".nav-item a").removeClass("active");


    $("#nav-item-data-referensi").addClass("menu-open");
    $("#nav-item-data-referensi > a").addClass("active");
    $("#nav-item-ref-organisasi > a").addClass("active");

    $('select').change(function(){
        //location.href = $(this).val();
    });

    $("#dtOrganisasi").DataTable({
      "responsive": true,
      "autoWidth": false,
    });

JS;
$this->inlineScript()->captureEnd();
