<?php
//print_r($this->hp1);
//print_r("<br/>");
//print_r($this->hp2);
?>
<div id="ribbon">

				<span class="ribbon-button-alignment">
					<span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
						<i class="fa fa-refresh"></i>
					</span>
				</span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
        <li>Setting</li><li>User</li><li>New User</li>
    </ol>
    <!-- end breadcrumb -->

    <!-- You can also add more buttons to the
            ribbon for further usability

            Example below:

            <span class="ribbon-button-alignment pull-right">
            <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
            <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
            <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
            </span> -->

</div>
<!-- END RIBBON -->

<!-- MAIN CONTENT -->
<div id="content">

    <div class="row">
        <!-- NEW COL START -->
        <article class="col-sm-12 col-md-12 col-lg-6">

            <!-- Widget ID (each widget will need unique ID)-->
            <div class="jarviswidget" id="wid-id-4" data-widget-editbutton="false" data-widget-custombutton="false">
                <!-- widget options:
                    usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                    data-widget-colorbutton="false"
                    data-widget-editbutton="false"
                    data-widget-togglebutton="false"
                    data-widget-deletebutton="false"
                    data-widget-fullscreenbutton="false"
                    data-widget-custombutton="false"
                    data-widget-collapsed="true"
                    data-widget-sortable="false"

                -->
                <header>
                    <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
                    <h2>Pendaftaran User Baru </h2>

                </header>

                <!-- widget div-->
                <div>

                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->

                    </div>
                    <!-- end widget edit box -->

                    <!-- widget content -->
                    <div class="widget-body no-padding">

                        <form id="frm_new_user" class="smart-form">
                            <header>
                                Formulir Pendaftaran
                            </header>

                            <fieldset>

                                <section>
                                    <label class="checkbox">
                                        <input type="checkbox" name="ldap" id="ldap">
                                        <i></i>Gunakan Username dan Password Email @kemlu.go.id</label>
                                </section>

                                <section class="non-ldap">
                                    <label class="input"> <i class="icon-append fa fa-user"></i>
                                        <input type="text" name="fullname" placeholder="Fullname">
                                        <b class="tooltip tooltip-bottom-right">Needed to enter the website</b> </label>
                                </section>

                                <section>
                                    <label class="input"> <i class="icon-append fa fa-envelope-o"></i>
                                        <input type="email" name="email" placeholder="Email address as Username">
                                        <b class="tooltip tooltip-bottom-right">Needed to verify your account</b> </label>
                                </section>

                                <section class="non-ldap">
                                    <label class="input"> <i class="icon-append fa fa-lock"></i>
                                        <input type="password" name="password" id="password" placeholder="Password" >
                                        <b class="tooltip tooltip-bottom-right">Don't forget your password</b> </label>
                                </section>

                                <section class="non-ldap">
                                    <label class="input"> <i class="icon-append fa fa-lock"></i>
                                        <input type="password" name="passwordConfirm" id="passwordConfirm" placeholder="Confirm password">
                                        <b class="tooltip tooltip-bottom-right">Don't forget your password</b> </label>
                                </section>
                            </fieldset>


                            <fieldset class="non-ldap">
                                <section >
                                    <label class="input"> <i class="icon-append fa fa-calendar"></i>
                                        <input type="text" name="request" placeholder="Request activation on" class="datepicker" data-dateformat='dd/mm/yy'>
                                    </label>
                                </section>
                            </fieldset>

                            <footer>
                                <button type="button" id="btn_simpan_user" class="btn btn-primary">
                                    Simpan
                                </button>
                            </footer>
                        </form>

                    </div>
                    <!-- end widget content -->

                </div>
                <!-- end widget div -->

            </div>
            <!-- end widget -->
        </article>

        <article class="col-sm-12 col-md-12 col-lg-6">

            <!-- Widget ID (each widget will need unique ID)-->
            <div class="jarviswidget" id="wid-id-4" data-widget-editbutton="false" data-widget-custombutton="false">
                <!-- widget options:
                    usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                    data-widget-colorbutton="false"
                    data-widget-editbutton="false"
                    data-widget-togglebutton="false"
                    data-widget-deletebutton="false"
                    data-widget-fullscreenbutton="false"
                    data-widget-custombutton="false"
                    data-widget-collapsed="true"
                    data-widget-sortable="false"

                -->
                <header>
                    <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
                    <h2> Detil User Baru </h2>
                </header>

                <!-- widget div-->
                <div>

                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->

                    </div>
                    <!-- end widget edit box -->

                    <!-- widget content -->
                    <div class="widget-body no-padding">

                        <form id="frm_new_user_role" class="smart-form">
                            <header>
                                Role dan Hak Akses
                            </header>

                            <fieldset>
                                <div class="row">
                                    <section class="col col-6">
                                        <label class="select">
                                            <select name="akses">
                                                <option value="0" selected="" disabled="">Pilih Akses</option>
                                                <option value="1">Akses semua kemlu</option>
                                                <option value="2">Akses Pusat</option>
                                                <option value="3">Akses Perwakilan</option>
                                                <option value="4">Akses Semua Satker</option>
                                            </select> <i></i> </label>
                                    </section>
                                    <section class="col-lg-2">
                                        <button type="button" class="btn btn-info btn-sm" data-toggle="#jobInfo">
                                            Tambah Akses
                                        </button>
                                    </section>

                                </div>
                            </fieldset>

                            <fieldset>
                                <div class="row">
                                    <section class="col col-6">
                                        <label class="select">
                                            <select name="role">
                                                <option value="0" selected="" disabled="">Pilih Role</option>
                                                <option value="1">role satu</option>
                                                <option value="2">role dua</option>
                                                <option value="3">role tiga</option>
                                            </select> <i></i> </label>
                                    </section>
                                    <section class="col-lg-2">
                                        <button type="button" class="btn btn-info btn-sm" data-toggle="#jobInfo">
                                            Tambah Role
                                        </button>
                                    </section>

                                </div>
                            </fieldset>

                        </form>

                    </div>
                    <!-- end widget content -->

                </div>
                <!-- end widget div -->

            </div>
            <!-- end widget -->
        </article>
    </div>
</div>
<?php
$this->headScript()->appendFile('/vendor/pustikkp/rbac/user.js?3');

