<?php
$optionPegawai = "";
foreach ($this->pegawai as $p ) {  
    $value = $p->getId();
    $text = '[' . $p->getNip().'] '.$p->getNamaDepan() .' -- ' . $p->getOrganisasi()->getNama();
    $optionPegawai .= "<option value='$value'>$text</option>";
}
?>
<div class="row">
<div class=" col-md-8 col-xs-12">
<div class="card card-primary">
    <div class="card-header">
    <h3 class="card-title">Formulir Periode Kegiatan Jabatan Fungsional</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" method="POST">
    <div class="card-body">
        <div class="form-group row">
            <label for="periode_mulai" class="col-4 col-form-label">Periode Mulai</label> 
            <div class="col-8">
            <div class="input-group">
                <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fa fa-calendar-alt"></i>
                </div>
                </div> 
                <input id="periode_mulai" name="periode_mulai" type="text" class="form-control datemask" data-inputmask-alias="datetime" data-inputmask-inputformat="dd/mm/yyyy" data-mask>                        </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="periode_akhir" class="col-4 col-form-label">Periode Akhir</label> 
            <div class="col-8">
            <div class="input-group">
                <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fa fa-calendar-alt"></i>
                </div>
                </div> 
                
                <input id="periode_akhir" name="periode_akhir" type="text" class="form-control datemask" data-inputmask-alias="datetime" data-inputmask-inputformat="dd/mm/yyyy" data-mask>            
            </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="atasan" class="col-4 col-form-label">Atasan</label> 
            <div class="col-8">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <i class="fa fa-user"></i>
                        </div>
                    </div>
                    <select class="custom-select select2" id="atasan" name="atasan">
                        <option selected>Pilih pegawai</option>
                        <?=$optionPegawai;?>
                    </select>
                </div>
            </div>
        </div> 
        <div class="form-group row">
            <label for="pengusul" class="col-4 col-form-label">Pejabat Pengusul</label> 
            <div class="col-8">
            <div class="input-group">
                <div class="input-group-prepend">
                        <div class="input-group-text">
                            <i class="fa fa-user"></i>
                        </div>
                    </div>
                    <select class="custom-select select2" id="pengusul" name="pengusul">
                        <option selected>Pilih pegawai</option>
                        <?=$optionPegawai;?>
                    </select>
                </div>
            </div>
        </div> 
        
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
        <button type="submit" class="btn btn-primary float-right">Simpan Periode Dupak</button>
    </div>
    </form>
</div>
<!-- /.card -->
</div>
</div>

<div class="row">
<div class=" col-md-8 col-xs-12">
<div class="card card-primary">
    <div class="card-header">
    <h3 class="card-title">Daftar Kegiatan</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form">
    <div class="card-body">
        
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    </form>
</div>
<!-- /.card -->
</div>
</div>

<?php
$this->inlineScript()->captureStart();
echo <<<JS

    $("#nav-item-dupak").addClass("menu-open");
    $("#nav-item-dupak > a").addClass("active");
    $("#nav-item-dupak-usulan > a").addClass("active");

    //Initialize Select2 Elements
    $('.select2').select2({
      theme: 'bootstrap4'
    })
    //Datemask dd/mm/yyyy
    $('.datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })

    
JS;
$this->inlineScript()->captureEnd();
