<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Selamat Datang<br>di Prototype Aplikasi Dupak Perencana Bappenas</h1>

    <p>
        Aplikasi ini dibuat oleh 
        <a href="https://www.linkedin.com/in/fathur-rohman-67337763/" target="_blank">Fathur Rohman</a>.
        sebagai bagian dari portofolio untuk bahan pertimbangan kesempatan menjadi tenaga ahli di Bappenas.
    </p>

    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="https://starganteknologi.com" target="_blank">Check Stargan Teknologi &raquo;</a>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Follow Development</h2>
        <div class="card-body">
            <p>
                E-dupak is under active development. If you are
                interested in following the development, you can contact me
                <a href="https://www.linkedin.com/in/fathur-rohman-67337763/" target="_blank"> on linkedin </a>.
                This project will be dedicated to Civil Servant for Managing Performance Record on activity task defined by each "Jabatan Fungsional".
            </p>

            <a class="btn btn-primary" href="https://github.com/vatoer" target="_blank">Will Be Hosted on github  &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">E-Dupak Modules</h2>
        <div class="card-body">
            <p>

                
                <ul>Module E-dupak terdiri atas: 
                <li>pengajuan dupak</li>
                <li>cetak dokumen dupak</li>
                <li>cetak SPMK</li>
                <li>Persetujuan Atasan</li>
                <li>Persetujuan Pejabat Unit Pengusul</li>
                <li>Pemeriksaan dokumen oleh Unit Pengampu Jafung</li>
                <li>Pembentukan Tim Penilai</li>
                <li>Penjadwalan Periode Dupak</li>
                <li>Penilaian </li>
                </ul>
            </p>

            <a class="btn btn-primary" href="https://packagist.org/?tags=module~zf2~zendframework~zend%20framework~zend%20framework%202~zf3~zf~zend~laminas" target="_blank">Explore Laminas Modules &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Help &amp; Support</h2>
        <div class="card-body">
            <p>
                If you need any help or support while developing with Laminas,
                you may reach us via <a href="https://laminas.dev/chat">chat</a> or
                <a href="https://discourse.laminas.dev">forum</a>.
                We'd love to hear any questions or feedback you may have
                regarding any release.
            </p>

            <a class="btn btn-primary" href="https://laminas.dev/chat" target="_blank">Ping us on chat &raquo;</a>
        </div>
    </div>
</div>
